{% set name = "shelflet" %}
{% set version = "0.1.4" %}
# {% set sha256 = "ae2cc83fb5a75e8dc3e1b2c2137deea412c8a4c7c9acca52bf4ec59de52a80c9" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz # [linux64]
  # If getting the source from GitHub remove the line above
  # uncomment the line below and modify as needed
  # url: https://github.com/simplejson/{{ name }}/archive/{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  # Uncomment the following line if the package is pure python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/meta.html#building-noarch-packages for more details.
  # noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  # script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}

test:
  imports:
    - shelflet
    - _gdbm

about:
  home: https://github.com/mullenkamp/shelflet
  license: Apache License 2.0
  license_family: APACHE
  summary: The Python shelve module except with optional serializers and compression to make smaller shelves!
  description: The Python shelve module except with optional serializers and compression to make smaller shelves! Also adds in the gdbm library...because it is not packaged with anaconda...
  doc_url: https://github.com/mullenkamp/shelflet
  dev_url: ''
